### ISSUE TITLE
Power Mode "Better Performance" Isn't available on my machine

### ISSUE THREAD

**Issue by Gnomey123** [Hepi34/PowerMode#1]
I've noticed on my Framework 16 Laptop, "Better Performance" isn't an option.

![image](https://github.com/user-attachments/assets/b82bbd2b-6641-414d-ad21-7b408cecd339)

The issue seems to be that some Laptops seem to have different power options, based on how the [vendors include firmware options](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/customize-power-slider)

However, According to [AaronKelley's Powermode repo:](https://github.com/AaronKelley/PowerMode)

![image](https://github.com/user-attachments/assets/5fa9b6e1-c50b-4147-bd7f-25b0248e3d66)

Yet I've figured out how to make it work!

```csharp       
        /// <summary>
        /// Retrieves a list of available power overlay schemes and their count.
        /// </summary>
        /// <param name="overlaySchemes">A pointer to a list of GUID structures. [The caller must free this memory]</param>
        /// <param name="schemeCount">The number of GUID overlay schemes retrieved.</param>
        /// <param name="filter">A filter or control flag. [Seems to have no effect]</param>
        /// <returns>Returns zero if the call was successful, and a nonzero value if the call failed.</returns>
        [DllImport("powrprof.dll", EntryPoint = "PowerGetOverlaySchemes", SetLastError = true)]
        private static extern uint PowerGetOverlaySchemes(
            out IntPtr overlaySchemes,
            out int schemeCount,
            byte filter
        );
```

And then, for using it:

```csharp
IntPtr overlaySchemes;
int schemeCount;
byte filter = 0; // Example filter value

result = PowerGetOverlaySchemes(out overlaySchemes, out schemeCount, filter);


if (result == 0) // Assuming 0 is success
{
    Console.WriteLine($"Retrieved {schemeCount} overlay schemes.");

    // Process the schemes (assuming GUIDs are stored, 16 bytes each)
    for (int i = 0; i < schemeCount; i++)
    {
        IntPtr schemePtr = IntPtr.Add(overlaySchemes, i * 16);
        Guid scheme = Marshal.PtrToStructure<Guid>(schemePtr);
        Console.WriteLine($"Scheme {i + 1}: {scheme}");
    }

    // Free allocated memory
    Marshal.FreeHGlobal(overlaySchemes);
}
else
{
    Console.WriteLine($"Failed to retrieve overlay schemes. Error code: {result}");
}
```

![image](https://github.com/user-attachments/assets/922a81c5-36f1-4f30-bab9-90fdff61dac4)

This outputs the GUID's for
 "961cc777-2547-4f9d-8174-7d86181b8a7a" [Better Battery]
 "ded574b5-45a0-4f42-8737-46345c09c238" [Best Performance]

Seems like it doesn't output the GUID for "Balanced", as it might be the default value that should always be available based on the fact that it's GUID is "00000000-0000-0000-0000-000000000000"

Could this be incorporated into the application? I'd make a pull request with my fork, but I'm having issues with compiling your code with the older dotnet 7.0 (although I'll keep trying when I get more time on my hands)

**Comment by Hepi34** [comment]
Alright, I've tried out your code to retrieve the available GUID's for my laptop. The code returned three GUID's, including the one for better battery (961cc777-2547-4f9d-8174-7d86181b8a7a), which isn't even an option on my laptop. Applying this GUID makes the power mode selector show nothing.

![image](https://github.com/user-attachments/assets/052de582-1d3e-426c-adae-17b1418020d2)

![image](https://github.com/user-attachments/assets/429ee20b-dfc9-458e-a572-5b821a0f7aee)

However, incorporating only showing the available powermodes into this app seems like a good idea and should still be possible. I could take a guess on what modes to show, going by the following logic: 

- If the "Better Performance" GUID (3af...) is listed, show that and label the default "000000..." GUID as "Recommended". Do not show the "Better Battery" option, but display "Best Performance".
- If the "Better Performance" GUID isn’t listed, show "Better Battery", label the middle option as "Balanced", and display "Best Performance".

Because according to the pictures that I could find online, the only two possible combinations that can appear in the selector are either "Better battery, Balanced and Best Performance" or "Recommended, Better Performance and Best Performance". With the GUID's you and me got, it seems like this logic should work.

I'll try to make the UI elements only show the available modes in the next couple of days when I'll have more time.

**Comment by Gnomey123** [comment]
Alright. I also am able to test AMD Radeon iGPU and dGPU, so I could look into trying to get that working.

**Comment by Hepi34** [comment]
I've implemented the feature to display only the available modes in the code and made a new commit. I also uploaded a new release. Please try it out and let me know if it doesn't work. I'll gladly try to fix any issues you encounter :)

Regarding AMD GPU auto-switching, I'd love to implement it, but I believe I would need an AMD GPU laptop to test on. The issue with detecting GPU load is that Windows often puts dGPUs to sleep when there's no load, with the iGPU handling light tasks instead. This is important for power savings, as the dGPU in laptops consumes a lot of power, even at minimal load. The conventional methods to detect GPU load would constantly wake the dGPU up, which would drain your battery quickly.

For NVIDIA GPUs, the method I use is querying the NVApi PerformanceStatesInfo command. If the GPU is sleeping, it will throw an error without waking the GPU, which avoids unnecessary power consumption.

I would need to find a similar method for AMD dGPUs, but unfortunately, I don't have access to an AMD dGPU laptop at the moment. I'll still try to find a solution, though. If I manage to find something, I’d be happy to accept your help in testing whether GPU polling works. If you find something, feel free to create a new issue or a PR, and I'll look at it to see if we can implement it your way.

**Comment by Hepi34** [comment]
Has this issue been fixed for you with the new commit / the new version of the app?

**Comment by Gnomey123** [comment]
It does indeed work correctly!
I was also able to compile and run the project in Visual Studio. 

As for the released code with the msix package and install.ps1, the powershell file complains about not finding a local package 
".\Add-AppDevPackage.ps1"
![image](https://github.com/user-attachments/assets/97098d97-2436-4081-b7d5-61bb6e4596c6)

Other then those, it works correctly!


Later this month (when my college semester ends), I'd love to further contribute to this project, implementing a better installer, de-compiling more of the "undocumented" dll functions, [possibly] update the dotnet version to 8, and yes, work on AMD dGPU (as the radeon software does show a pop-up when it switches to dGPU, so there must be an official way to determin)

**Comment by Hepi34** [comment]
Great to hear that it works!

About the installation issue: I'll probably buy a Microsoft store license this weekend, so I will be able to release my app to the Microsoft store. Then no one will have to deal with installation issues again.

Helping with the AMD dGPU issue is also nice, so thank you for offering you help.
